config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: [:index, :show, :create] do
    resources :bookmarks, only: [:create]
  end
    resources :bookmarks, only:  [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :list_id, :movie_id, presence: true
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmarks_params)
    @movie = Movie.find(params[:bookmark][:movie_id])
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    @bookmark.movie = @movie
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render "lists/show"
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmarks_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @list = List.new
  end

  def new
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @movie = Movie.new
  end

  def create
    @lists = List.all
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render 'index'
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div id = "new_bookmark">
  <h1> New Bookmark </h1>

  <%= simple_form_for(@bookmark) do |f| %>
    <%= f.input :name %>
    <%= f.association :movies, input_html: { class: 'select2' } %>
    <%= f.submit 'Create bookmark', :class => 'btn btn-success' %>

    <div> <%= link_to "Back to bookmark", lists_path, class: 'btn btn-primary' %> </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" id='home-banner' style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1536440136628-849c177e76a1?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8bW92aWVzfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60);">
  <div class="container">
    <h1>Save your movies </h1>
    <p>
      <span id="banner-typed-text"></span>
    </p>
  </div>
</div>

<div class = "container">
  <div class = 'd-flex justify-content-around align-items-center m-10'>
    <h2> My lists (<%= @lists.size %>) </h2>
    <div>
      <%= simple_form_for(@list) do |f| %>
      <%= f.input_field :name, placeholder: 'list name' %>
      <%= f.input_field :photo, as: :file %>
      <%= f.submit 'Create list', :class => 'btn btn-primary' %>
    <% end %>
    </div>
  </div>
  <div class = 'lists'>
    <% @lists.each do |list| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>')">
      <%= link_to list.name, list_path(list), class: 'category-name' %>
    </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
    <div> <%= link_to "Back to list", lists_path, class: 'btn btn-primary' %> </div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key, width: 3000, crop: :fill %>')">
  <div class = "container">
    <h1> <%= @list.name %> </h1>
  </div>
</div>

<div class = "bookmarks">
  <% @list.bookmarks.each do |bookmark| %>
  <div class="flip-card">
    <div class="flip-card-inner">
      <div class="flip-card-front" style="background-image: url(<%= bookmark.movie.poster_url %>)"></div>
      <div class="flip-card-back" style="background-image: linear-gradient(rgba(0,0,0,0.7), rgba(0,0,0,0.7)), url(<%= bookmark.movie.poster_url %>)">
        <h2> <%= bookmark.movie.title %></h2>
        <div>
        <%= bookmark.movie.rating %>
        <i class="fas fa-star"></i>
        </div>
        <div class = bookmark>
          <div>
            <i class="fas fa-video"></i>
            <%= bookmark.comment %>
          </div>
          <%= link_to "Remove", bookmark_path(bookmark), method: :delete, class: 'btn btn-danger', style: 'font-size: 12px;', data: { confirm: "Are you sure?" } %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

<div class = 'form'>
  <h1> New Bookmark </h1>

    <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie, input_html: { class: 'select2' } %>
    <%= f.submit 'Create bookmark', :class => 'btn btn-success' %>
    <% end %>

  <div> <%= link_to "Back to list", lists_path, class: 'btn btn-primary' %> </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon fixed-top">
  <h2> Watch list </h2>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "My list", lists_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "https://avatars.githubusercontent.com/u/80259966?v=4", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Action", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>